import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fallen Codes",
  description: "Generated by create next app",
};
const menuType = ["Movies", "Genres"]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar menuType={menuType} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
